language: python
before_install:
- sudo apt-get update
- sudo apt-get install python
- sudo apt-get install python-fontforge
install:
- pip install -q -e .
python:
- '2.7'
script:
- python runtests.py
deploy:
  provider: pypi
  user: dalou
  password:
    secure: NEjTiHcBQIJac3+wyYpBqOz3v6O2vCM/nKgGeM6WD/yJNV181Y9nu8kUUP/4Ws0Uc1YXca150aL46F+TZpQFDyrFRpKN7UwQS6mH3vf16QeSJZVDZNqKgP8yC4b3lvawrAle7ElvBLeFhrFB4y7f9bgLbYHKxfhG7wvbWWJJOBqOEF2h4goIk1kXmW6pOcYYiuUyee7UaMgtftMBgIvwf5NPRsEMUFpx/oZn+/BPi3so38uZd0l83DSepEV7ZbCAvO79P1zQiw7mWvnRBQ54tNrcm7G2OWHb80c5pSton7hVqbd1cR2xNtstb15OBGufcln1hmeuYUZQzRRB+W4NTf8JBMF2qKi3Vt2MOAd0EdDoztV+u5lRPmdcjGQbpbDuFxpmTQ41JPsa2/hGrBpH0w3kY2fGzJdl17cigu+HVsi1b8DfJUakwSdlYb61khFt75qRq+8hemScjBWcGSuurTBU3hPoibNdsOV/Sn8kbuVtqKb7KAo79sVmD9NLlpwYS6uvN0UNjc7aJh4ZIwnWWSLB+S5hvQJckkmYYaf0ouim7UhxeOj5sts9YduMZXaaaMHSQw3KqkWwXgeFYDO4v2nB4sBaKM8Q+KBOUrgkBVR2LdoXXdkSK9WNtnMc12oY7p5t6cbktYj6JIKgRTdpyrTe4ZUa1LAz+3K8lFubGZ4=
  on:
    branch: all_branches
    tags: true
