language: python
before_install:
- sudo apt-get update
- sudo apt-get install python
- sudo apt-get install python-fontforge
install:
- pip install -q -e .
python:
- '2.7'
script:
- python runtests.py
deploy:
  provider: pypi
  user: dalou
  password:
    secure: TpJLQsOjYjdIFHj9IxuvXNDJAQ+dtH6A0Mdsa2+sGeyt34P7ZIvg150KwannfksrImWBulDHnNjbF5evBBFT0685RkwDTTuMJieo7F1kJgJTffztaaTrDWF6TN1iZNS1IfTT2Kp2CCDdSds4C0YJ62F3OEyxU52Ms5LRP2DlSqsxJmzM6O+8Atur6yOeohnsQaBEBFCR+aF+hDSkikgElssGORiahQZOBKxLhVPFShubMcTrL03D2kk+NRp1sF6SA/o8D5h4iEHYx3NI/1dQKO/1WekTtDYtU1NedJPhhVhZKE12KptXCAXTdstGY0nbRVpVRleoYgTmjQbRyKnsaPsbkPTErVn1Ei5+vBOtVmBb9OoLaOnwtJgAz4H2xi5iPY+MI3WaXRbl4NYYc9oRFUP2BE+jf7/34DmN1t9Fm4OVxVp84+J9XBb8GCdKes3iEHSo+LlX0CX72lhiOUIT/vwTkT2yXiZ7AEldNuxhDh/s0uYYp8IbYJ3ihWIum1/IdYgYnjOB50E4BkptxhdxlVuWvtBtbEsmvq3n52OnYhSdvit7tJb3vTsJ5yIQ3p/2x3I6sbS4Ck3ltziL14rop1auXMOw+G6HhMa72TAAHdSpUE7Mpd99hSi1xqL6tmTGVGEqTaRPyUQMsDJ9vrU6d3IbI1upDpFp6dKQWm3lV0U=
  on:
    branch: all_branches
    tags: true
